Fixed Node-crashing TypeError; typos; camelCase
# TypeError
When running this as a dependency with the GrovePi, Node consistently crashed with the following message:
`
/home/pi/.../node_modules/node-grovepi/sensors/digitalButton.js:27
               var milliseconds = currentDateTime.getTime() - pressedDateTime.getTime()
{ imagine an arrow pointing up at the dot "." in "pressedDateTime.getTime() }
TypeError: Cannot read property 'getTime of undefined
`
...whenever I tried pressing and holding the button to trigger my main program's event.
Defining the three variables involved at the top (instead of within the `if` statement) and changing all `let`s to `var`s fixed this problem.

# Typos
"miliseconds" (sic) -> "milliseconds"

# camelCase
"longpressDelay" -> "longPressDelay"
"datetimePressed" -> pressedDateTime  { matches format already used for "currentDateTime" }